version: '3'
services:
  nginx:
    user: "${UID}:${GID}"
    image: evild/alpine-nginx:1.9.15-openssl
    container_name: estatetrack_nginx
    restart: "no"
    links:
      - php
    volumes:
      - ./:/var/www/html/:ro
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8095:80
    depends_on:
      - db
      - php
  php:
    user: "${UID}:${GID}"
    build: docker/php
    container_name: estatetrack_php
    restart: "no"

    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_NAME=estatetrack
      - DB_HOST=lemp
      - DB_PASSWORD=password
  db:
    user: "${UID}:${GID}"
    image: mariadb:latest
    container_name: estatetrack_mariadb
    restart: "no"
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local

networks:
  default:
    external:
      name: dev1
  dev1:
    external: true